# Generated by Django 4.1 on 2022-09-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="database",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kword", models.CharField(max_length=30, primary_key=True)),
                ("time", models.DateTimeField()),
            ],
        ),
    ]
